//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the semantic_label_3d package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __semantic_label_3d__LABELVIEWERCONFIG_H__
#define __semantic_label_3d__LABELVIEWERCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace semantic_label_3d
{
  class labelviewerConfigStatics;
  
  class labelviewerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(labelviewerConfig &config, const labelviewerConfig &max, const labelviewerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const labelviewerConfig &config1, const labelviewerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, labelviewerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const labelviewerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, labelviewerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const labelviewerConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T labelviewerConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (labelviewerConfig::* field);

      virtual void clamp(labelviewerConfig &config, const labelviewerConfig &max, const labelviewerConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const labelviewerConfig &config1, const labelviewerConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, labelviewerConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const labelviewerConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, labelviewerConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const labelviewerConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 15 "cfg/labelviewer.cfg"
      std::string red_label;
//#line 16 "cfg/labelviewer.cfg"
      std::string green_label;
//#line 17 "cfg/labelviewer.cfg"
      std::string blue_label;
//#line 18 "cfg/labelviewer.cfg"
      std::string yellow_label;
//#line 19 "cfg/labelviewer.cfg"
      std::string cyan_label;
//#line 20 "cfg/labelviewer.cfg"
      std::string magenta_label;
//#line 21 "cfg/labelviewer.cfg"
      std::string dark_red_label;
//#line 22 "cfg/labelviewer.cfg"
      std::string dark_green_label;
//#line 23 "cfg/labelviewer.cfg"
      std::string dark_blue_label;
//#line 24 "cfg/labelviewer.cfg"
      std::string dark_yellow_label;
//#line 26 "cfg/labelviewer.cfg"
      bool showLabel;
//#line 27 "cfg/labelviewer.cfg"
      std::string message_orig;
//#line 28 "cfg/labelviewer.cfg"
      std::string message_pred;
//#line 29 "cfg/labelviewer.cfg"
      int segmentNum;
//#line 30 "cfg/labelviewer.cfg"
      bool showSegment;
//#line 31 "cfg/labelviewer.cfg"
      bool done;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("labelviewerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const labelviewerConfig &__max__ = __getMax__();
      const labelviewerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const labelviewerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const labelviewerConfig &__getDefault__();
    static const labelviewerConfig &__getMax__();
    static const labelviewerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const labelviewerConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void labelviewerConfig::ParamDescription<std::string>::clamp(labelviewerConfig &config, const labelviewerConfig &max, const labelviewerConfig &min) const
  {
    return;
  }

  class labelviewerConfigStatics
  {
    friend class labelviewerConfig;
    
    labelviewerConfigStatics()
    {
//#line 15 "cfg/labelviewer.cfg"
      __min__.red_label = "";
//#line 15 "cfg/labelviewer.cfg"
      __max__.red_label = "";
//#line 15 "cfg/labelviewer.cfg"
      __default__.red_label = "label";
//#line 15 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<std::string>("red_label", "str", 0, "label", "", &labelviewerConfig::red_label)));
//#line 16 "cfg/labelviewer.cfg"
      __min__.green_label = "";
//#line 16 "cfg/labelviewer.cfg"
      __max__.green_label = "";
//#line 16 "cfg/labelviewer.cfg"
      __default__.green_label = "label";
//#line 16 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<std::string>("green_label", "str", 0, "label", "", &labelviewerConfig::green_label)));
//#line 17 "cfg/labelviewer.cfg"
      __min__.blue_label = "";
//#line 17 "cfg/labelviewer.cfg"
      __max__.blue_label = "";
//#line 17 "cfg/labelviewer.cfg"
      __default__.blue_label = "label";
//#line 17 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<std::string>("blue_label", "str", 0, "label", "", &labelviewerConfig::blue_label)));
//#line 18 "cfg/labelviewer.cfg"
      __min__.yellow_label = "";
//#line 18 "cfg/labelviewer.cfg"
      __max__.yellow_label = "";
//#line 18 "cfg/labelviewer.cfg"
      __default__.yellow_label = "label";
//#line 18 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<std::string>("yellow_label", "str", 0, "label", "", &labelviewerConfig::yellow_label)));
//#line 19 "cfg/labelviewer.cfg"
      __min__.cyan_label = "";
//#line 19 "cfg/labelviewer.cfg"
      __max__.cyan_label = "";
//#line 19 "cfg/labelviewer.cfg"
      __default__.cyan_label = "label";
//#line 19 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<std::string>("cyan_label", "str", 0, "label", "", &labelviewerConfig::cyan_label)));
//#line 20 "cfg/labelviewer.cfg"
      __min__.magenta_label = "";
//#line 20 "cfg/labelviewer.cfg"
      __max__.magenta_label = "";
//#line 20 "cfg/labelviewer.cfg"
      __default__.magenta_label = "label";
//#line 20 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<std::string>("magenta_label", "str", 0, "label", "", &labelviewerConfig::magenta_label)));
//#line 21 "cfg/labelviewer.cfg"
      __min__.dark_red_label = "";
//#line 21 "cfg/labelviewer.cfg"
      __max__.dark_red_label = "";
//#line 21 "cfg/labelviewer.cfg"
      __default__.dark_red_label = "label";
//#line 21 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<std::string>("dark_red_label", "str", 0, "label", "", &labelviewerConfig::dark_red_label)));
//#line 22 "cfg/labelviewer.cfg"
      __min__.dark_green_label = "";
//#line 22 "cfg/labelviewer.cfg"
      __max__.dark_green_label = "";
//#line 22 "cfg/labelviewer.cfg"
      __default__.dark_green_label = "label";
//#line 22 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<std::string>("dark_green_label", "str", 0, "label", "", &labelviewerConfig::dark_green_label)));
//#line 23 "cfg/labelviewer.cfg"
      __min__.dark_blue_label = "";
//#line 23 "cfg/labelviewer.cfg"
      __max__.dark_blue_label = "";
//#line 23 "cfg/labelviewer.cfg"
      __default__.dark_blue_label = "label";
//#line 23 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<std::string>("dark_blue_label", "str", 0, "label", "", &labelviewerConfig::dark_blue_label)));
//#line 24 "cfg/labelviewer.cfg"
      __min__.dark_yellow_label = "";
//#line 24 "cfg/labelviewer.cfg"
      __max__.dark_yellow_label = "";
//#line 24 "cfg/labelviewer.cfg"
      __default__.dark_yellow_label = "label";
//#line 24 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<std::string>("dark_yellow_label", "str", 0, "label", "", &labelviewerConfig::dark_yellow_label)));
//#line 26 "cfg/labelviewer.cfg"
      __min__.showLabel = 0;
//#line 26 "cfg/labelviewer.cfg"
      __max__.showLabel = 1;
//#line 26 "cfg/labelviewer.cfg"
      __default__.showLabel = 0;
//#line 26 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<bool>("showLabel", "bool", 0, "Display label?", "", &labelviewerConfig::showLabel)));
//#line 27 "cfg/labelviewer.cfg"
      __min__.message_orig = "";
//#line 27 "cfg/labelviewer.cfg"
      __max__.message_orig = "";
//#line 27 "cfg/labelviewer.cfg"
      __default__.message_orig = "";
//#line 27 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<std::string>("message_orig", "str", 0, "", "", &labelviewerConfig::message_orig)));
//#line 28 "cfg/labelviewer.cfg"
      __min__.message_pred = "";
//#line 28 "cfg/labelviewer.cfg"
      __max__.message_pred = "";
//#line 28 "cfg/labelviewer.cfg"
      __default__.message_pred = "";
//#line 28 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<std::string>("message_pred", "str", 0, "", "", &labelviewerConfig::message_pred)));
//#line 29 "cfg/labelviewer.cfg"
      __min__.segmentNum = 0;
//#line 29 "cfg/labelviewer.cfg"
      __max__.segmentNum = 30000000;
//#line 29 "cfg/labelviewer.cfg"
      __default__.segmentNum = 0;
//#line 29 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<int>("segmentNum", "int", 0, "segment type", "", &labelviewerConfig::segmentNum)));
//#line 30 "cfg/labelviewer.cfg"
      __min__.showSegment = 0;
//#line 30 "cfg/labelviewer.cfg"
      __max__.showSegment = 1;
//#line 30 "cfg/labelviewer.cfg"
      __default__.showSegment = 0;
//#line 30 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<bool>("showSegment", "bool", 0, "Display Segment?", "", &labelviewerConfig::showSegment)));
//#line 31 "cfg/labelviewer.cfg"
      __min__.done = 0;
//#line 31 "cfg/labelviewer.cfg"
      __max__.done = 1;
//#line 31 "cfg/labelviewer.cfg"
      __default__.done = 0;
//#line 31 "cfg/labelviewer.cfg"
      __param_descriptions__.push_back(labelviewerConfig::AbstractParamDescriptionConstPtr(new labelviewerConfig::ParamDescription<bool>("done", "bool", 0, "Done?", "", &labelviewerConfig::done)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<labelviewerConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<labelviewerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    labelviewerConfig __max__;
    labelviewerConfig __min__;
    labelviewerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const labelviewerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static labelviewerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &labelviewerConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const labelviewerConfig &labelviewerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const labelviewerConfig &labelviewerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const labelviewerConfig &labelviewerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<labelviewerConfig::AbstractParamDescriptionConstPtr> &labelviewerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const labelviewerConfigStatics *labelviewerConfig::__get_statics__()
  {
    const static labelviewerConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = labelviewerConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __LABELVIEWERRECONFIGURATOR_H__
