//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the semantic_label_3d package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __semantic_label_3d__PCMERGERCONFIG_H__
#define __semantic_label_3d__PCMERGERCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace semantic_label_3d
{
  class pcmergerConfigStatics;
  
  class pcmergerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(pcmergerConfig &config, const pcmergerConfig &max, const pcmergerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const pcmergerConfig &config1, const pcmergerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, pcmergerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const pcmergerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, pcmergerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const pcmergerConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T pcmergerConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (pcmergerConfig::* field);

      virtual void clamp(pcmergerConfig &config, const pcmergerConfig &max, const pcmergerConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const pcmergerConfig &config1, const pcmergerConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, pcmergerConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const pcmergerConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, pcmergerConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const pcmergerConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 14 "cfg/pcmerger.cfg"
      double x;
//#line 15 "cfg/pcmerger.cfg"
      double y;
//#line 16 "cfg/pcmerger.cfg"
      double z;
//#line 17 "cfg/pcmerger.cfg"
      double yaw;
//#line 18 "cfg/pcmerger.cfg"
      double pitch;
//#line 19 "cfg/pcmerger.cfg"
      double roll;
//#line 20 "cfg/pcmerger.cfg"
      double minx;
//#line 21 "cfg/pcmerger.cfg"
      double maxx;
//#line 22 "cfg/pcmerger.cfg"
      double miny;
//#line 23 "cfg/pcmerger.cfg"
      double maxy;
//#line 24 "cfg/pcmerger.cfg"
      double minz;
//#line 25 "cfg/pcmerger.cfg"
      double maxz;
//#line 31 "cfg/pcmerger.cfg"
      bool add_pc;
//#line 32 "cfg/pcmerger.cfg"
      bool undo;
//#line 33 "cfg/pcmerger.cfg"
      bool skip_pc;
//#line 34 "cfg/pcmerger.cfg"
      bool update;
//#line 35 "cfg/pcmerger.cfg"
      bool setIT;
//#line 36 "cfg/pcmerger.cfg"
      double skipNum;
//#line 37 "cfg/pcmerger.cfg"
      bool set_skip;
//#line 38 "cfg/pcmerger.cfg"
      bool done;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("pcmergerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const pcmergerConfig &__max__ = __getMax__();
      const pcmergerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const pcmergerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const pcmergerConfig &__getDefault__();
    static const pcmergerConfig &__getMax__();
    static const pcmergerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const pcmergerConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void pcmergerConfig::ParamDescription<std::string>::clamp(pcmergerConfig &config, const pcmergerConfig &max, const pcmergerConfig &min) const
  {
    return;
  }

  class pcmergerConfigStatics
  {
    friend class pcmergerConfig;
    
    pcmergerConfigStatics()
    {
//#line 14 "cfg/pcmerger.cfg"
      __min__.x = -1000.0;
//#line 14 "cfg/pcmerger.cfg"
      __max__.x = 1000.0;
//#line 14 "cfg/pcmerger.cfg"
      __default__.x = 0.0;
//#line 14 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<double>("x", "double", 0, "x", "", &pcmergerConfig::x)));
//#line 15 "cfg/pcmerger.cfg"
      __min__.y = -1000.0;
//#line 15 "cfg/pcmerger.cfg"
      __max__.y = 1000.0;
//#line 15 "cfg/pcmerger.cfg"
      __default__.y = 0.0;
//#line 15 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<double>("y", "double", 0, "y", "", &pcmergerConfig::y)));
//#line 16 "cfg/pcmerger.cfg"
      __min__.z = -1000.0;
//#line 16 "cfg/pcmerger.cfg"
      __max__.z = 1000.0;
//#line 16 "cfg/pcmerger.cfg"
      __default__.z = 0.0;
//#line 16 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<double>("z", "double", 0, "z", "", &pcmergerConfig::z)));
//#line 17 "cfg/pcmerger.cfg"
      __min__.yaw = -180.0;
//#line 17 "cfg/pcmerger.cfg"
      __max__.yaw = 180.0;
//#line 17 "cfg/pcmerger.cfg"
      __default__.yaw = 50.0;
//#line 17 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<double>("yaw", "double", 0, "yaw", "", &pcmergerConfig::yaw)));
//#line 18 "cfg/pcmerger.cfg"
      __min__.pitch = -180.0;
//#line 18 "cfg/pcmerger.cfg"
      __max__.pitch = 180.0;
//#line 18 "cfg/pcmerger.cfg"
      __default__.pitch = 0.0;
//#line 18 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<double>("pitch", "double", 0, "pitch", "", &pcmergerConfig::pitch)));
//#line 19 "cfg/pcmerger.cfg"
      __min__.roll = -180.0;
//#line 19 "cfg/pcmerger.cfg"
      __max__.roll = 180.0;
//#line 19 "cfg/pcmerger.cfg"
      __default__.roll = -115.0;
//#line 19 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<double>("roll", "double", 0, "roll", "", &pcmergerConfig::roll)));
//#line 20 "cfg/pcmerger.cfg"
      __min__.minx = -5.0;
//#line 20 "cfg/pcmerger.cfg"
      __max__.minx = 10.0;
//#line 20 "cfg/pcmerger.cfg"
      __default__.minx = -5.0;
//#line 20 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<double>("minx", "double", 0, "minx", "", &pcmergerConfig::minx)));
//#line 21 "cfg/pcmerger.cfg"
      __min__.maxx = -5.0;
//#line 21 "cfg/pcmerger.cfg"
      __max__.maxx = 10.0;
//#line 21 "cfg/pcmerger.cfg"
      __default__.maxx = 10.0;
//#line 21 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<double>("maxx", "double", 0, "maxx", "", &pcmergerConfig::maxx)));
//#line 22 "cfg/pcmerger.cfg"
      __min__.miny = -5.0;
//#line 22 "cfg/pcmerger.cfg"
      __max__.miny = 10.0;
//#line 22 "cfg/pcmerger.cfg"
      __default__.miny = -5.0;
//#line 22 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<double>("miny", "double", 0, "miny", "", &pcmergerConfig::miny)));
//#line 23 "cfg/pcmerger.cfg"
      __min__.maxy = -5.0;
//#line 23 "cfg/pcmerger.cfg"
      __max__.maxy = 10.0;
//#line 23 "cfg/pcmerger.cfg"
      __default__.maxy = 10.0;
//#line 23 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<double>("maxy", "double", 0, "maxy", "", &pcmergerConfig::maxy)));
//#line 24 "cfg/pcmerger.cfg"
      __min__.minz = -5.0;
//#line 24 "cfg/pcmerger.cfg"
      __max__.minz = 5.0;
//#line 24 "cfg/pcmerger.cfg"
      __default__.minz = -5.0;
//#line 24 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<double>("minz", "double", 0, "minz", "", &pcmergerConfig::minz)));
//#line 25 "cfg/pcmerger.cfg"
      __min__.maxz = -5.0;
//#line 25 "cfg/pcmerger.cfg"
      __max__.maxz = 5.0;
//#line 25 "cfg/pcmerger.cfg"
      __default__.maxz = 5.0;
//#line 25 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<double>("maxz", "double", 0, "maxz", "", &pcmergerConfig::maxz)));
//#line 31 "cfg/pcmerger.cfg"
      __min__.add_pc = 0;
//#line 31 "cfg/pcmerger.cfg"
      __max__.add_pc = 1;
//#line 31 "cfg/pcmerger.cfg"
      __default__.add_pc = 0;
//#line 31 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<bool>("add_pc", "bool", 0, "add point cloud?", "", &pcmergerConfig::add_pc)));
//#line 32 "cfg/pcmerger.cfg"
      __min__.undo = 0;
//#line 32 "cfg/pcmerger.cfg"
      __max__.undo = 1;
//#line 32 "cfg/pcmerger.cfg"
      __default__.undo = 0;
//#line 32 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<bool>("undo", "bool", 0, "Undo?", "", &pcmergerConfig::undo)));
//#line 33 "cfg/pcmerger.cfg"
      __min__.skip_pc = 0;
//#line 33 "cfg/pcmerger.cfg"
      __max__.skip_pc = 1;
//#line 33 "cfg/pcmerger.cfg"
      __default__.skip_pc = 0;
//#line 33 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<bool>("skip_pc", "bool", 0, "skip point cloud?", "", &pcmergerConfig::skip_pc)));
//#line 34 "cfg/pcmerger.cfg"
      __min__.update = 0;
//#line 34 "cfg/pcmerger.cfg"
      __max__.update = 1;
//#line 34 "cfg/pcmerger.cfg"
      __default__.update = 0;
//#line 34 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<bool>("update", "bool", 0, "update point cloud?", "", &pcmergerConfig::update)));
//#line 35 "cfg/pcmerger.cfg"
      __min__.setIT = 0;
//#line 35 "cfg/pcmerger.cfg"
      __max__.setIT = 1;
//#line 35 "cfg/pcmerger.cfg"
      __default__.setIT = 0;
//#line 35 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<bool>("setIT", "bool", 0, "set Initial Transform?", "", &pcmergerConfig::setIT)));
//#line 36 "cfg/pcmerger.cfg"
      __min__.skipNum = 0.0;
//#line 36 "cfg/pcmerger.cfg"
      __max__.skipNum = 100.0;
//#line 36 "cfg/pcmerger.cfg"
      __default__.skipNum = 5.0;
//#line 36 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<double>("skipNum", "double", 0, "skipNum", "", &pcmergerConfig::skipNum)));
//#line 37 "cfg/pcmerger.cfg"
      __min__.set_skip = 0;
//#line 37 "cfg/pcmerger.cfg"
      __max__.set_skip = 1;
//#line 37 "cfg/pcmerger.cfg"
      __default__.set_skip = 0;
//#line 37 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<bool>("set_skip", "bool", 0, "set skip size?", "", &pcmergerConfig::set_skip)));
//#line 38 "cfg/pcmerger.cfg"
      __min__.done = 0;
//#line 38 "cfg/pcmerger.cfg"
      __max__.done = 1;
//#line 38 "cfg/pcmerger.cfg"
      __default__.done = 0;
//#line 38 "cfg/pcmerger.cfg"
      __param_descriptions__.push_back(pcmergerConfig::AbstractParamDescriptionConstPtr(new pcmergerConfig::ParamDescription<bool>("done", "bool", 0, "Done?", "", &pcmergerConfig::done)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<pcmergerConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<pcmergerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    pcmergerConfig __max__;
    pcmergerConfig __min__;
    pcmergerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const pcmergerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static pcmergerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &pcmergerConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const pcmergerConfig &pcmergerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const pcmergerConfig &pcmergerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const pcmergerConfig &pcmergerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<pcmergerConfig::AbstractParamDescriptionConstPtr> &pcmergerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const pcmergerConfigStatics *pcmergerConfig::__get_statics__()
  {
    const static pcmergerConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = pcmergerConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __PCMERGERRECONFIGURATOR_H__
